markdown: rdiscount
permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: mHealthDemoCamp
url: http://mhealthdemocamp.com
description: Mobile Health Demo camp
twitter: mHealthDemoCamp
